# Generated by Django 6.0.1 on 2026-02-07 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_type', models.CharField(choices=[('Individual', 'Individual'), ('Organization', 'Organization')], max_length=20)),
                ('organization_name', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='abcd.user')),
            ],
            options={
                'db_table': 'donors',
            },
        ),
    ]
