# Generated by Django 6.0.1 on 2026-02-07 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcd', '0002_donor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=150)),
                ('receiver_type', models.CharField(choices=[('NGO', 'NGO'), ('Shelter', 'Shelter'), ('Orphanage', 'Orphanage')], max_length=20)),
                ('registration_no', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='abcd.user')),
            ],
            options={
                'db_table': 'receivers',
            },
        ),
    ]
