# Generated by Django 6.0.1 on 2026-02-08 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcd', '0005_logistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_type', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('condition', models.CharField(choices=[('New', 'New'), ('Good', 'Good'), ('Usable', 'Usable')], max_length=10)),
                ('pickup_required', models.BooleanField(default=False)),
                ('donation_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Collected', 'Collected'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abcd.donor')),
            ],
            options={
                'db_table': 'donations',
            },
        ),
    ]
