# Generated by Django 6.0.1 on 2026-02-08 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcd', '0006_donations'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.TextField()),
                ('pickup_date', models.DateField()),
                ('pickup_status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='abcd.donations')),
            ],
            options={
                'db_table': 'pickup_requests',
            },
        ),
    ]
