# Generated by Django 6.0.1 on 2026-02-08 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcd', '0007_pickuprequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiverRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_type', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('request_date', models.DateField()),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Fulfilled', 'Fulfilled')], default='Approved', max_length=20)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abcd.receiver')),
            ],
            options={
                'db_table': 'receiver_requests',
            },
        ),
    ]
