# Generated by Django 6.0.1 on 2026-02-08 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcd', '0008_receiverrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskType', models.CharField(choices=[('Collection', 'Collection'), ('Sorting', 'Sorting'), ('Delivery', 'Delivery')], max_length=20)),
                ('taskStatus', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abcd.donations')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abcd.volunteer')),
            ],
            options={
                'db_table': 'task_assignment',
            },
        ),
    ]
