# Generated by Django 6.0.1 on 2026-02-08 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcd', '0009_taskassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryDate', models.DateField()),
                ('deliveryStatus', models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abcd.donations')),
                ('logistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abcd.logistics')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abcd.receiver')),
            ],
            options={
                'db_table': 'delivery',
            },
        ),
    ]
