# Generated by Django 6.0.1 on 2026-02-09 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcd', '0010_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothType', models.CharField(max_length=100)),
                ('availableQuantity', models.IntegerField()),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abcd.donor'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abcd.user'),
        ),
        migrations.AlterField(
            model_name='logistics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abcd.user'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abcd.user'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abcd.user'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('feedbackDate', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abcd.user')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportType', models.CharField(choices=[('Donation', 'Donation'), ('Receiver', 'Receiver'), ('Volunteer', 'Volunteer')], max_length=100)),
                ('generatedDate', models.DateField(auto_now_add=True)),
                ('generatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abcd.user')),
            ],
            options={
                'db_table': 'reports',
            },
        ),
    ]
