# Generated by Django 6.0.1 on 2026-02-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('duration', models.IntegerField(help_text='Duration in days')),
            ],
            options={
                'db_table': 'Servicee',
            },
        ),
    ]
