# Generated by Django 6.0.1 on 2026-02-06 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_category_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachername', models.CharField(max_length=100)),
                ('teacherage', models.IntegerField()),
                ('teacheremail', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherSubject', models.CharField(choices=[('maths', 'maths'), ('science', 'science'), ('english', 'english')], max_length=100)),
                ('teacherPhone', models.CharField(max_length=10)),
                ('teacherAddress', models.CharField(max_length=100)),
                ('teacherGender', models.CharField(max_length=10)),
                ('teacherDOB', models.DateField()),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.teacher')),
            ],
            options={
                'db_table': 'teacherprofile',
            },
        ),
    ]
