# Generated by Django 6.0.1 on 2026-02-06 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_teacher_teacherprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalName', models.CharField(max_length=100)),
                ('hospitalAddress', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'hospital',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorName', models.CharField(max_length=100)),
                ('doctorPhone', models.CharField(max_length=10)),
                ('doctorSpecialization', models.CharField(choices=[('cardio', 'cardio'), ('ortho', 'ortho'), ('neuro', 'neuro')], max_length=50)),
                ('hospitalId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.hospital')),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
    ]
