# Generated by Django 6.0.1 on 2026-02-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_hospital_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospitalstatus',
            field=models.BooleanField(default=True),
        ),
    ]
